version: '2'
services:
    logngateway-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/LogNGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=LogNGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
